### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by Nisarg03** [Hetarth02/sphinx-web-app#1]
There is a missing feature of 'Forgot Password?' in the login tab. It'd be helpful to your less bright users, unlike me. I remember all my passwords.

**Comment by Hetarth02** [comment]
I have added forgot password functionality.  Enter your registered username and email and it will send you an temporary password to you registered email address. Feel free to let me know if you want to add another feature or better make a PR if you want to contribute.
